// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Pessoa.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Pessoa TABLE
class TablePessoa extends SqfEntityTableBase {
  TablePessoa() {
    // declare properties of EntityTable
    tableName = 'pessoa';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('nome', DbType.text),
      SqfEntityFieldBase('sobrenome', DbType.text),
      SqfEntityFieldBase('idade', DbType.real),
      SqfEntityFieldBase('peso', DbType.real),
      SqfEntityFieldBase('altura', DbType.real),
      SqfEntityFieldBase('genero', DbType.text),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TablePessoa();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class AppDatabase extends SqfEntityModelProvider {
  AppDatabase() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    preSaveAction = myDbModel.preSaveAction;
    logFunction = myDbModel.logFunction;
    databaseTables = [
      TablePessoa.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = myDbModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Pessoa
class Pessoa extends TableBase {
  Pessoa(
      {this.id,
      this.nome,
      this.sobrenome,
      this.idade,
      this.peso,
      this.altura,
      this.genero}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  Pessoa.withFields(this.nome, this.sobrenome, this.idade, this.peso,
      this.altura, this.genero) {
    _setDefaultValues();
  }
  Pessoa.withId(this.id, this.nome, this.sobrenome, this.idade, this.peso,
      this.altura, this.genero) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Pessoa.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['nome'] != null) {
      nome = o['nome'].toString();
    }
    if (o['sobrenome'] != null) {
      sobrenome = o['sobrenome'].toString();
    }
    if (o['idade'] != null) {
      idade = double.tryParse(o['idade'].toString());
    }
    if (o['peso'] != null) {
      peso = double.tryParse(o['peso'].toString());
    }
    if (o['altura'] != null) {
      altura = double.tryParse(o['altura'].toString());
    }
    if (o['genero'] != null) {
      genero = o['genero'].toString();
    }
  }
  // FIELDS (Pessoa)
  int? id;
  String? nome;
  String? sobrenome;
  double? idade;
  double? peso;
  double? altura;
  String? genero;

  // end FIELDS (Pessoa)

  static const bool _softDeleteActivated = false;
  PessoaManager? __mnPessoa;

  PessoaManager get _mnPessoa {
    return __mnPessoa = __mnPessoa ?? PessoaManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (nome != null || !forView) {
      map['nome'] = nome;
    }
    if (sobrenome != null || !forView) {
      map['sobrenome'] = sobrenome;
    }
    if (idade != null || !forView) {
      map['idade'] = idade;
    }
    if (peso != null || !forView) {
      map['peso'] = peso;
    }
    if (altura != null || !forView) {
      map['altura'] = altura;
    }
    if (genero != null || !forView) {
      map['genero'] = genero;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (nome != null || !forView) {
      map['nome'] = nome;
    }
    if (sobrenome != null || !forView) {
      map['sobrenome'] = sobrenome;
    }
    if (idade != null || !forView) {
      map['idade'] = idade;
    }
    if (peso != null || !forView) {
      map['peso'] = peso;
    }
    if (altura != null || !forView) {
      map['altura'] = altura;
    }
    if (genero != null || !forView) {
      map['genero'] = genero;
    }

    return map;
  }

  /// This method returns Json String [Pessoa]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Pessoa]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [nome, sobrenome, idade, peso, altura, genero];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [id, nome, sobrenome, idade, peso, altura, genero];
  }

  static Future<List<Pessoa>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Pessoa.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Pessoa>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Pessoa>[];
    try {
      objList = list
          .map((pessoa) => Pessoa.fromMap(pessoa as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Pessoa.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Pessoa>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Pessoa> objList = <Pessoa>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Pessoa.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Pessoa by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [Pessoa] if exist, otherwise returns null
  Future<Pessoa?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    Pessoa? obj;
    final data = await _mnPessoa.getById([id]);
    if (data.length != 0) {
      obj = Pessoa.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Pessoa) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnPessoa.insert(this, ignoreBatch);
    } else {
      await _mnPessoa.update(this);
    }

    return id;
  }

  /// Saves the (Pessoa) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnPessoa.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnPessoa.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs Pessoa. Returns a new Primary Key value of Pessoa

  /// <returns>Returns a new Primary Key value of Pessoa
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<Pessoa> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Pessoa> pessoas,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await AppDatabase().batchStart();
    for (final obj in pessoas) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await AppDatabase().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < pessoas.length; i++) {
        if (pessoas[i].id == null) {
          pessoas[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnPessoa.rawInsert(
          'INSERT OR REPLACE INTO pessoa (id, nome, sobrenome, idade, peso, altura, genero)  VALUES (?,?,?,?,?,?,?)',
          [id, nome, sobrenome, idade, peso, altura, genero],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Pessoa id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Pessoa id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Pessoa Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Pessoa>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<Pessoa> pessoas,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnPessoa.rawInsertAll(
        'INSERT OR REPLACE INTO pessoa (id, nome, sobrenome, idade, peso, altura, genero)  VALUES (?,?,?,?,?,?,?)',
        pessoas,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes Pessoa

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete Pessoa invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnPessoa
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnPessoa.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [Pessoa] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  PessoaFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return PessoaFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  PessoaFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return PessoaFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion pessoa

// region PessoaField
class PessoaField extends FilterBase {
  PessoaField(PessoaFilterBuilder pessoaFB) : super(pessoaFB);

  @override
  PessoaFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder isNull() {
    return super.isNull() as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as PessoaFilterBuilder;
  }

  @override
  PessoaField get not {
    return super.not as PessoaField;
  }
}
// endregion PessoaField

// region PessoaFilterBuilder
class PessoaFilterBuilder extends ConjunctionBase {
  PessoaFilterBuilder(Pessoa obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnPessoa = obj._mnPessoa;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  PessoaManager? _mnPessoa;

  /// put the sql keyword 'AND'
  @override
  PessoaFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  PessoaFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  PessoaFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  PessoaFilterBuilder where(String? whereCriteria, {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  PessoaFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  PessoaFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  PessoaFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  PessoaFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  PessoaFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  PessoaFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  PessoaFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  PessoaField _setField(PessoaField? field, String colName, DbType dbtype) {
    return PessoaField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  PessoaField? _id;
  PessoaField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  PessoaField? _nome;
  PessoaField get nome {
    return _nome = _setField(_nome, 'nome', DbType.text);
  }

  PessoaField? _sobrenome;
  PessoaField get sobrenome {
    return _sobrenome = _setField(_sobrenome, 'sobrenome', DbType.text);
  }

  PessoaField? _idade;
  PessoaField get idade {
    return _idade = _setField(_idade, 'idade', DbType.real);
  }

  PessoaField? _peso;
  PessoaField get peso {
    return _peso = _setField(_peso, 'peso', DbType.real);
  }

  PessoaField? _altura;
  PessoaField get altura {
    return _altura = _setField(_altura, 'altura', DbType.real);
  }

  PessoaField? _genero;
  PessoaField get genero {
    return _genero = _setField(_genero, 'genero', DbType.text);
  }

  /// Deletes List<Pessoa> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnPessoa!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnPessoa!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from pessoa ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnPessoa!.updateBatch(qparams, values);
  }

  /// This method always returns [Pessoa] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Pessoa?
  @override
  Future<Pessoa?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnPessoa!.toList(qparams);
    final data = await objFuture;
    Pessoa? obj;
    if (data.isNotEmpty) {
      obj = Pessoa.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [Pessoa]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Pessoa?
  @override
  Future<Pessoa> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        Pessoa();
  }

  /// This method returns int. [Pessoa]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? pessoaCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final pessoasFuture = await _mnPessoa!.toList(qparams);
    final int count = pessoasFuture[0]['CNT'] as int;
    if (pessoaCount != null) {
      pessoaCount(count);
    }
    return count;
  }

  /// This method returns List<Pessoa> [Pessoa]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<Pessoa>
  @override
  Future<List<Pessoa>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Pessoa> pessoasData = await Pessoa.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return pessoasData;
  }

  /// This method returns Json String [Pessoa]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Pessoa]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Pessoa]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnPessoa!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Pessoa]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM pessoa WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnPessoa!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Pessoa]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnPessoa!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await Pessoa.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnPessoa!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion PessoaFilterBuilder

// region PessoaFields
class PessoaFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fNome;
  static TableField get nome {
    return _fNome = _fNome ?? SqlSyntax.setField(_fNome, 'nome', DbType.text);
  }

  static TableField? _fSobrenome;
  static TableField get sobrenome {
    return _fSobrenome = _fSobrenome ??
        SqlSyntax.setField(_fSobrenome, 'sobrenome', DbType.text);
  }

  static TableField? _fIdade;
  static TableField get idade {
    return _fIdade =
        _fIdade ?? SqlSyntax.setField(_fIdade, 'idade', DbType.real);
  }

  static TableField? _fPeso;
  static TableField get peso {
    return _fPeso = _fPeso ?? SqlSyntax.setField(_fPeso, 'peso', DbType.real);
  }

  static TableField? _fAltura;
  static TableField get altura {
    return _fAltura =
        _fAltura ?? SqlSyntax.setField(_fAltura, 'altura', DbType.real);
  }

  static TableField? _fGenero;
  static TableField get genero {
    return _fGenero =
        _fGenero ?? SqlSyntax.setField(_fGenero, 'genero', DbType.text);
  }
}
// endregion PessoaFields

//region PessoaManager
class PessoaManager extends SqfEntityProvider {
  PessoaManager()
      : super(AppDatabase(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'pessoa';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion PessoaManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await AppDatabaseSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await AppDatabaseSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await AppDatabaseSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class AppDatabaseSequenceManager extends SqfEntityProvider {
  AppDatabaseSequenceManager() : super(AppDatabase());
}
// END OF ENTITIES
